### ISSUE TITLE
Image3dAPI - Conversion from Raw DICOM to VolDICOM

### ISSUE THREAD

**Issue by tchen87** [MedicalUltrasound/Image3dAPI#157]
@forderud In a conversation I had with Sergio (from EchoPixel), he mentioned that you told him there is some capability for Image3dAPI to convert Raw DICOM files to VolDICOM format. In looking through the code base, I wasn't able to find anything like this.

Can you please clarify if this functionality exists?

**Comment by forderud** [comment]
This is a cross-vendor Image3dApi repository for API definitions and sample code. Questions regarding individual vendor's rawdata formats and SW offerings will need to the directed directly towards each vendor.
