### ISSUE TITLE
Problem building Image3dAPI

### ISSUE THREAD

**Issue by TKhienwad** [MedicalUltrasound/Image3dAPI#170]
Hi,

I tried to build your code in Virtual Studio but I got 10 errors. Could you please help me solve this issue.

![image](https://user-images.githubusercontent.com/87311899/133447171-412c9b5b-28cf-4295-82ee-e70cf8d1d829.png)

Best regards,

Thananya

**Comment by forderud** [comment]
Apologies for the inconvenience. I've submitted a fix on https://github.com/MedicalUltrasound/Image3dAPI/pull/171 that should hopefully be merged later today.

**Comment by TKhienwad** [comment]
Thank you every much for your time. 

Best, 

Thananya

**Comment by forderud** [comment]
Closing issue as fixed.
