### ISSUE TITLE
Physical size of the volume

### ISSUE THREAD

**Issue by mr-BM** [MedicalUltrasound/Image3dAPI#172]
I try to extract the 3D+t volume from a GE ultrasound dicom. I was able to save the 3D image arrays using the `source.GetFrameCount()` function, but I am confused about the physical size of the volume.

I used 200 as the _max_image_res_ parameter, but I afraid that I loose image information with this size. I would need the size of the volume or bbox (in meters or millimeters)  and the pixel spacing (in millimeter) to calculate the right _max_image_res_ value.

The `source.GetBoundingBox()` function returns _dir_ values. These are the size of the bounding box in meter (e.g. dir1_x = 0.15130 means that the width of the volume is around 15 cm)?

Also, how can I extract the pixel spacing of the 3D volume?

**Comment by forderud** [comment]
> The `source.GetBoundingBox()` function returns _dir_ values. These are the size of the bounding box in meter (e.g. dir1_x = 0.15130 means that the width of the volume is around 15 cm)?

Correct.

> Also, how can I extract the pixel spacing of the 3D volume?

There's not correct answer to that question. Any selected resolution will involve a tradeoff between memory consumption and resolution degradation. The reason for this is that ultrasound "rawdata" is internally stored beam-by-beam in within the file. These beams are typically arranged in a quasi-polar coordinate-system. The spatial resolution is therefore higher near the probe (where the beams are closer) than further down into the image (where the beams are wider apart).

**Comment by forderud** [comment]
I would recommend you to also take a look at the `GetBoundingBox` API doc on https://github.com/MedicalUltrasound/Image3dAPI/blob/master/Image3dAPI/IImage3d.idl#L292

**Comment by balint-argus** [comment]
I see, thank you. So lets say that I have a bounding box, where the maximum value is 0.15 and I set the _max_image_res_ to 150, int this case one voxel will be 1x1x1 mm. Is that correct?

**Comment by mr-BM** [comment]
I see, thank you. So lets say that I have a bounding box, where the maximum value is 0.15 and I set the _max_image_res_ to 150. In this case one voxel will cover a volume of 1x1x1 mm. Is that correct?

**Comment by forderud** [comment]
> I see, thank you. So lets say that I have a bounding box, where the maximum value is 0.15 and I set the _max_image_res_ to 150. In this case one voxel will cover a volume of 1x1x1 mm. Is that correct?

Almost correct. You'll then request 1mm voxel size. However, the volume you actually get _might_ have lower resolution if the loader DLL imposes resolution limitations.
