### ISSUE TITLE
GE 3D ultrasound processing "Read stitched volume data failed. dcm::incompatible_data thrown"

### ISSUE THREAD

**Issue by mr-BM** [MedicalUltrasound/Image3dAPI#173]
I tried to extract the 3D+t volume from GE ultrasound dicoms and in most of the cases it worked perfectly, but in some cases I got the following errors:

"Read stitched volume data failed. dcm::incompatible_data thrown (read_stitched_frame: Found sub volume 3 more than once)."
or
"Read stitched volume data failed. dcm::incompatible_data thrown (get_stitching_times: Too few cine-loops)."

What can be the problem with these dicoms?

**Comment by forderud** [comment]
Apologies, but it sounds like you're trying to open incomplete or corrupted data. There's not unfortunately not much we can do about that.
