### ISSUE TITLE
".rgs" files not found while building

### ISSUE THREAD

**Issue by Kamlesh364** [MedicalUltrasound/Image3dAPI#180]
Build started...
------ Build started: Project: Image3dAPI, Configuration: Debug Win32 ------
Processing .\IImage3d.idl
IImage3d.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl
oaidl.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl
objidl.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl
unknwn.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl
wtypes.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl
wtypesbase.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h
basetsd.h
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h
guiddef.h
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf
oaidl.acf
Processing .\IImage3dTypeLibraryGenerator.idl
IImage3dTypeLibraryGenerator.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl
oaidl.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl
objidl.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl
unknwn.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl
wtypes.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl
wtypesbase.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h
basetsd.h
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h
guiddef.h
Processing .\IImage3d.idl
IImage3d.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf
oaidl.acf
Microsoft (R) .NET Framework Type Library to Assembly Converter 4.8.3928.0
Copyright (C) Microsoft Corporation.  All rights reserved.

TlbImp : Type library imported to C:\Users\patel\Documents\Image3DAPI\Win32\Debug\Image3dAPI.dll
Win32\Debug\IImage3d.h
Win32\Debug\IImage3dTypeLibraryGenerator.h
2 File(s) copied
Win32\Debug\dlldata.c
Win32\Debug\IImage3dTypeLibraryGenerator_i.c
Win32\Debug\IImage3d_i.c
Win32\Debug\IImage3d_p.c
4 File(s) copied
C:\Users\patel\Documents\Image3DAPI\Win32\Debug\Image3dAPI.tlb
1 File(s) copied
C:\Users\patel\Documents\Image3DAPI\Win32\Debug\Image3dAPI.dll
1 File(s) copied
------ Build started: Project: DummyLoader, Configuration: Debug Win32 ------
------ Build started: Project: TestViewer, Configuration: Debug x86 ------
Generate RGS-files
Processing .\DummyLoader.idl
DummyLoader.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl
oaidl.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl
objidl.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl
unknwn.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl
wtypes.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl
wtypesbase.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h
basetsd.h
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h
guiddef.h
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ocidl.idl
ocidl.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oleidl.idl
oleidl.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\servprov.idl
servprov.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\urlmon.idl
urlmon.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\msxml.idl
msxml.idl
  TestViewer -> C:\Users\patel\Documents\Image3DAPI\TestViewer\bin\x86\Debug\TestViewer.exe
Processing C:\Users\patel\Documents\Image3DAPI\DummyLoader\..\Image3dAPI\IImage3d.idl
IImage3d.idl
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf
oaidl.acf
Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ocidl.acf
ocidl.acf
Image3dFileLoader.cpp
Image3dSource.cpp
Image3dStream.cpp
Main.cpp
Generating Code...

**DummyLoader.rc(61): error RC2135: file not found: Image3dSource.rgs**
**DummyLoader.rc(62): error RC2135: file not found: Image3dFileLoader.rgs**

**Done building project "DummyLoader.vcxproj" -- FAILED.**
------ Build started: Project: RegFreeTest, Configuration: Debug Win32 ------
------ Build started: Project: SandboxTest, Configuration: Debug Win32 ------

Main.cpp
Main.cpp

**LINK : fatal error LNK1104: cannot open file 'C:\Users\patel\Documents\Image3DAPI\Win32\Debug\DummyLoaderD.dll.manifest'**

Done building project "RegFreeTest.vcxproj" -- FAILED.

SandboxTest.vcxproj -> C:\Users\patel\Documents\Image3DAPI\Win32\Debug\SandboxTest.exe

========== **Build: 3 succeeded, 2 failed, 0 up-to-date, 0 skipped** ==========

**Comment by forderud** [comment]
Extract from https://github.com/MedicalUltrasound/Image3dAPI#getting-started
`Python.exe need to be registered as default app for running .py scripts. This can be done by right-clicking on a .py file, then selecting "Open with", "Choose another app", locate Python.exe and enable "Always use this app to open .py files".`

Can you please check if this is the underlying problem?

**Comment by Kamlesh364** [comment]
**Done building project "DummyLoader.vcxproj" -- FAILED.**
------ Build started: Project: RegFreeTest, Configuration: Debug Win32 ------
------ Build started: Project: SandboxTest, Configuration: Debug Win32 ------
Main.cpp
Main.cpp
RegFreeTest.vcxproj -> C:\Users\patel\Documents\Image3DAPI\Win32\Debug\RegFreeTest.exe
SandboxTest.vcxproj -> C:\Users\patel\Documents\Image3DAPI\Win32\Debug\SandboxTest.exe
========== Build: 4 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

> Extract from https://github.com/MedicalUltrasound/Image3dAPI#getting-started `Python.exe need to be registered as default app for running .py scripts. This can be done by right-clicking on a .py file, then selecting "Open with", "Choose another app", locate Python.exe and enable "Always use this app to open .py files".`
> 
> Can you please check if this is the underlying problem?

**Comment by Kamlesh364** [comment]
> **Done building project "DummyLoader.vcxproj" -- FAILED.** ------ Build started: Project: RegFreeTest, Configuration: Debug Win32 ------ ------ Build started: Project: SandboxTest, Configuration: Debug Win32 ------ Main.cpp Main.cpp RegFreeTest.vcxproj -> C:\Users\patel\Documents\Image3DAPI\Win32\Debug\RegFreeTest.exe SandboxTest.vcxproj -> C:\Users\patel\Documents\Image3DAPI\Win32\Debug\SandboxTest.exe ========== Build: 4 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> 
> > Extract from https://github.com/MedicalUltrasound/Image3dAPI#getting-started `Python.exe need to be registered as default app for running .py scripts. This can be done by right-clicking on a .py file, then selecting "Open with", "Choose another app", locate Python.exe and enable "Always use this app to open .py files".`
> > Can you please check if this is the underlying problem?

@forderud this error is still there after following your suggestion.

**Comment by forderud** [comment]
You probably need to clean your git workspace and then rebuild from scratch.

**Comment by Kamlesh364** [comment]
I've tried that way, it's not working.

**Comment by forderud** [comment]
The only way you're going to get `DummyLoader.rc(61): error RC2135: file not found: Image3dSource.rgs
` errors is if the `GenRgsFiles.py` pre-build step is _not_ run.

**Comment by Kamlesh364** [comment]
Build started...
------ Build started: Project: Image3dAPI, Configuration: Debug x64 ------
64 bit Processing .\IImage3d.idl
IImage3d.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl
oaidl.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl
objidl.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl
unknwn.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl
wtypes.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl
wtypesbase.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h
basetsd.h
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h
guiddef.h
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf
oaidl.acf
64 bit Processing .\IImage3dTypeLibraryGenerator.idl
IImage3dTypeLibraryGenerator.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl
oaidl.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl
objidl.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl
unknwn.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl
wtypes.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl
wtypesbase.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h
basetsd.h
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h
guiddef.h
64 bit Processing .\IImage3d.idl
IImage3d.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf
oaidl.acf
Microsoft (R) .NET Framework Type Library to Assembly Converter 4.8.3928.0
Copyright (C) Microsoft Corporation.  All rights reserved.

TlbImp : Type library imported to C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\Image3dAPI.dll
x64\Debug\IImage3d.h
x64\Debug\IImage3dTypeLibraryGenerator.h
2 File(s) copied
x64\Debug\dlldata.c
x64\Debug\IImage3dTypeLibraryGenerator_i.c
x64\Debug\IImage3d_i.c
x64\Debug\IImage3d_p.c
4 File(s) copied
C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\Image3dAPI.tlb
1 File(s) copied
C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\Image3dAPI.dll
1 File(s) copied
------ Build started: Project: DummyLoader, Configuration: Debug x64 ------
------ Build started: Project: TestViewer, Configuration: Debug x64 ------
Generate RGS-files
64 bit Processing .\DummyLoader.idl
DummyLoader.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl
oaidl.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl
objidl.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl
unknwn.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl
wtypes.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl
wtypesbase.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h
basetsd.h
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h
guiddef.h
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ocidl.idl
ocidl.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oleidl.idl
oleidl.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\servprov.idl
servprov.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\urlmon.idl
urlmon.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\msxml.idl
msxml.idl
64 bit Processing C:\Users\patel\Documents\Image3dAPI-master\DummyLoader\..\Image3dAPI\IImage3d.idl
  TestViewer -> C:\Users\patel\Documents\Image3dAPI-master\TestViewer\bin\x64\Debug\TestViewer.exe
IImage3d.idl
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf
oaidl.acf
64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ocidl.acf
ocidl.acf
Image3dFileLoader.cpp
Image3dSource.cpp
Image3dStream.cpp
Main.cpp
Generating Code...
   Creating library C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.lib and object C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.exp
DummyLoader.vcxproj -> C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.dll
echo Registering component
Registering DLL...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: The command "IF DynamicLibrary == DynamicLibrary (
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075:   echo Registering DLL...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075:   regsvr32 /s "C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.dll"
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: ) ELSE (
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075:   echo Registering EXE...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075:   "C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.dll" /regserver
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: )
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: :VCEnd" exited with code 5. Please verify that you have sufficient rights to run this command.
**Done building project "DummyLoader.vcxproj" -- FAILED.**
------ Build started: Project: RegFreeTest, Configuration: Debug x64 ------
------ Build started: Project: SandboxTest, Configuration: Debug x64 ------
Main.cpp
Main.cpp
RegFreeTest.vcxproj -> C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\RegFreeTest.exe
SandboxTest.vcxproj -> C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\SandboxTest.exe
========== Build: 4 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Kamlesh364** [comment]
@forderud please check the current log, I've tried cleaning up workspace that's not working.

> Build started... ------ Build started: Project: Image3dAPI, Configuration: Debug x64 ------ 64 bit Processing .\IImage3d.idl IImage3d.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl oaidl.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl objidl.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl unknwn.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl wtypes.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl wtypesbase.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h basetsd.h 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h guiddef.h 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf oaidl.acf 64 bit Processing .\IImage3dTypeLibraryGenerator.idl IImage3dTypeLibraryGenerator.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl oaidl.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl objidl.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl unknwn.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl wtypes.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl wtypesbase.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h basetsd.h 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h guiddef.h 64 bit Processing .\IImage3d.idl IImage3d.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf oaidl.acf Microsoft (R) .NET Framework Type Library to Assembly Converter 4.8.3928.0 Copyright (C) Microsoft Corporation. All rights reserved.
> 
> TlbImp : Type library imported to C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\Image3dAPI.dll x64\Debug\IImage3d.h x64\Debug\IImage3dTypeLibraryGenerator.h 2 File(s) copied x64\Debug\dlldata.c x64\Debug\IImage3dTypeLibraryGenerator_i.c x64\Debug\IImage3d_i.c x64\Debug\IImage3d_p.c 4 File(s) copied C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\Image3dAPI.tlb 1 File(s) copied C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\Image3dAPI.dll 1 File(s) copied ------ Build started: Project: DummyLoader, Configuration: Debug x64 ------ ------ Build started: Project: TestViewer, Configuration: Debug x64 ------ Generate RGS-files 64 bit Processing .\DummyLoader.idl DummyLoader.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.idl oaidl.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\objidl.idl objidl.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\unknwn.idl unknwn.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypes.idl wtypes.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\wtypesbase.idl wtypesbase.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\basetsd.h basetsd.h 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\guiddef.h guiddef.h 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ocidl.idl ocidl.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oleidl.idl oleidl.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\servprov.idl servprov.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\urlmon.idl urlmon.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\msxml.idl msxml.idl 64 bit Processing C:\Users\patel\Documents\Image3dAPI-master\DummyLoader..\Image3dAPI\IImage3d.idl TestViewer -> C:\Users\patel\Documents\Image3dAPI-master\TestViewer\bin\x64\Debug\TestViewer.exe IImage3d.idl 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\oaidl.acf oaidl.acf 64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\ocidl.acf ocidl.acf Image3dFileLoader.cpp Image3dSource.cpp Image3dStream.cpp Main.cpp Generating Code... Creating library C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.lib and object C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.exp DummyLoader.vcxproj -> C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.dll echo Registering component Registering DLL... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: The command "IF DynamicLibrary == DynamicLibrary ( C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: echo Registering DLL... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: regsvr32 /s "C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.dll" C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: ) ELSE ( C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: echo Registering EXE... C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: "C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\DummyLoaderD.dll" /regserver C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: ) C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3075: :VCEnd" exited with code 5. Please verify that you have sufficient rights to run this command. **Done building project "DummyLoader.vcxproj" -- FAILED.** ------ Build started: Project: RegFreeTest, Configuration: Debug x64 ------ ------ Build started: Project: SandboxTest, Configuration: Debug x64 ------ Main.cpp Main.cpp RegFreeTest.vcxproj -> C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\RegFreeTest.exe SandboxTest.vcxproj -> C:\Users\patel\Documents\Image3dAPI-master\x64\Debug\SandboxTest.exe ========== Build: 4 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by forderud** [comment]
Quote from https://github.com/MedicalUltrasound/Image3dAPI#getting-started: `Open Visual Studio with administrative privileges.`

Closing, since the reported problems disappear if reading the getting started instructions.
