### ISSUE TITLE
How to use TestViewer?

### ISSUE THREAD

**Issue by Kamlesh364** [MedicalUltrasound/Image3dAPI#181]
@forderud would you please instruct how to use TestViewer?

**Comment by forderud** [comment]
What´s your problem? Loader selection, file loading or image viewing?

**Comment by Kamlesh364** [comment]
I'm actually not getting for what purpose ImageViewer is there, whether it'd provide some kind of interface to use the whole implementation. Can we zip this whole project into ".exe" or some other application format for summarized use or not? If yes, How?

**Comment by forderud** [comment]
This repo isn't targeting end-users. It's targeting developers that are either developing or integrating Image3dAPI loaders. TestViewer is a test tool for qualification testing of loaders developed by the major ultrasound companies. It's not intended as a end-user applicating for viewing 3D ultrasound data.

**Comment by rodrigogplima** [comment]
Sorry I do not understand. I think they're looking for the wrong person.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
