### ISSUE TITLE
unclear how to build 3dimageAPI

### ISSUE THREAD

**Issue by cardio75** [MedicalUltrasound/Image3dAPI#185]
Hello,
(not a Professional developer here).
I obtained the GE loader, registred it with regsrvc then proceeded to build 3DimageAPI
There are errors during build about the dummy loader.
What to do if I don't need the dummy loader to have a build complete.
How will Slicer3D use Image3dAPI ?
 what does this line in the GE loader Readme means ? : 3: Create loader object based on "GEHC_CARD_US.Image3dFileLoader" ProgID string in client project.
Thank you for your help (I just want to load 3D images in Slicer)

**Comment by forderud** [comment]
Sorry, but this repository does _not_ target end-users. It targets _developers_ that are either interested in developing a new loader like the GE loader, or in adding Image3dAPI support to client SW like 3D slicer.

You'll furthermore need to contact GE for questions related to their loader.

**Comment by tbirdso** [comment]
@cardio75 For questions about 3D Slicer you can start a discussion thread in the [3D Slicer Discourse](https://discourse.slicer.org/) or open an issue at the [SlicerHeart](https://github.com/SlicerHeart/SlicerHeart) module repository.

Related reading: https://github.com/SlicerHeart/SlicerHeart/blob/master/Docs/ImageImportExport.md#ge

**Comment by cardio75** [comment]
Thank you @tbirdso . I understand now that SlicerHeart  in 3D Slicer already incorporates Image3DApi. Theri is no need to build it.
This was not immediately clear for me.
My issue is resolved
