### ISSUE TITLE
API: Switch to DICOM standard coordinates

### ISSUE THREAD

**Issue by forderud** [MedicalUltrasound/Image3dAPI#88]
Swap X,Y,Z axes, so that it becomes consistent with the DICOM standards:
![image](https://user-images.githubusercontent.com/2671400/45484737-7c480d00-b755-11e8-8d9e-b14f3f65c9e6.png)

Retrieved from Link: ftp://medical.nema.org/medical/dicom/final/sup43_ft.doc (page 40).

**Comment by forderud** [comment]
@SteveKauffman Would it be possible for you to update this issue with more information and link to relevant parts of the DICOM standard?

**Comment by SteveKauffman** [comment]
DICOM Enhanced Ultrasound (sup 43) issues:

Per Supplement 43:
A.X.4.1.2 Plane Position (Volume) and Plane Orientation (Volume) Macros Image Position (Volume) (0020,9301) first value (X) shall be zero and second value (Y) shall be zero. Image Orientation (Volume) (0020,9302) values shall be 1\0\0\0\1\0. This ensures that the origins of each frame lies on the Volume Frame of Reference ZV axis, the rows of each frame are parallel to the Volume Frame of Reference XV axis, and the columns of each frame are parallel to the Volume Frame of  Reference YV axis.

See also:
C.8.X.2.1 Ultrasound Frame of Reference Module Overview The Ultrasound Frame of Reference Module is used to relate the image planes to a frame of reference appropriate for the ultrasound modality, most notably a volume-based frame of reference. There are many different transducer scan acquisition geometries used in 3D ultrasound imaging. Regardless of the acquisition geometry, after acquisition of the initial scan images comprising the volume, the ultrasound (US) scanner will assemble (reformat) the data into a proper Cartesian volume with the assumption that the data are related through a Right-Hand Coordinate System (RHCS). x-positions are defined in mm with positive values increasing towards the right. y-positions are defined in mm with positive values in the direction of increasing image depth. z-positions are defined in mm with positive values in the direction as defined in a right-hand coordinate system.

And diagram on page 40 at C.8.X.2.1.1 Volume Frame of Reference.

 Z
/
/
-----------X
|    /\
|   /  \
|  /____\
Y


Open4D is different:

 Y
/
/
-----------X
|    /\
|   /  \
|  /____\
Z


Suggest changing to Sup43 way.
