### ISSUE TITLE
API: Improve error messages on loader failure

### ISSUE THREAD

**Issue by forderud** [MedicalUltrasound/Image3dAPI#97]
Introduce error codes for:
* File not found/unable to open
* Missing private DICOM tags. (incompatible)
* Loader outdated (unable to load file that is too new)

More??

**Comment by SteveKauffman** [comment]
I'd left this as feedback for pull request #102:

API change proposal: I think that providing enum-based return values would indeed be helpful, especially in providing localized error messages to users. However, I think if we eliminate the ability to send a freeform string from the loader to the client, we'll lose a valuable channel for debugging issues when something goes wrong.

Perhaps we should retain the 'error_message' field as an [out] param, while adding the 'error' as the [out,retval] field. This would allow a hosting application to provide a localized "unsupported file" message, while also providing a detailed message like "Emage doesn't contain the 200d,003d tag containing 3D image data. Ensure that the image was exported with 3D native data" (or a call-stack or other error detail). The detailed message could be logged by the hosting application, or could be displayed along with the localized message to the user, similar to the way an exception dialog displays both a generic message, and exception details.

**Comment by forderud** [comment]
@SteveKauffman Good suggestions. I've now tried to address your comment and updated the PR. Can you please have a second look at it?
